owner: FullControlMTG
repo: upptime

sites:
  - name: FullControlMTG Website
    url: https://www.fullcontrolmtg.com
  - name: FullControlMTG Cube Tracker Website
    url: https://cube.fullcontrolmtg.com

status-website:
  cname: status.fullcontrolmtg.com
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: FullControlMTG Status Page
  introTitle: "Status page and uptime tracker for **FullControlMTG**, powered by Upptime."
  introMessage: This status page tracks status and website health for the various FullControlMTG websites.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
